### ISSUE TITLE
Problem with generating setters/getters for properties with generic types

### ISSUE THREAD

**Issue by pkorzeniewski** [enriquein/JavaSetterGetter#5]
Example:

``` java
Map<Object,String> mp;
```

Plugin won't generate setter/getter for such property. To fix this issue I had to change line 11 from

``` python
"(?: (?P<type>[a-zA-Z0-9_$]+))" + \
```

to

``` python
"(?: (?P<type>[a-zA-Z0-9_$\<\>\,\s]+))" + \
```

**Comment by enriquein** [comment]
Thanks for the snippet. Your fix went live with the 1.4.0 release. Many, many thanks for catching that.
