### ISSUE TITLE
Did not work

### ISSUE THREAD

**Issue by advaittrivedi** [enriquein/JavaSetterGetter#8]
I installed this plugin, I got the message at the bottom of the screen saying javasettergetter installed successfully. But I neither I got Java under tools menu nor ctrl+k ctrl+j shortcuts work for me. I am on sublime version 3.0.1 build 2217 for win.

**Comment by enriquein** [comment]
I'm not sure the plugin would work with Sublime Text 3. I haven't given it
a shot yet or even looked at the API yet. For the time being I can only say
it's compatible with version 2 and that's about it.

On Tuesday, June 4, 2013, advaittrivedi wrote:

> I installed this plugin, I got the message at the bottom of the screen
> saying javasettergetter installed successfully. But I neither I got Java
> under tools menu nor ctrl+k ctrl+j shortcuts work for me. I am on sublime
> version 3.0.1 build 2217 for win.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/enriquein/JavaSetterGetter/issues/8
> .

## 

---

Enrique Ramirez Irizarry
Software Developer

**Comment by alvinsim** [comment]
I have the same issue but I am on Sublime version 2.0.1 build 2217 for windows. This is the error I see from the console:

ignored packages updated to: [Vintage, SublimeJava, JavaSetterGetter]
found 1 files for base name Default.sublime-theme
Exception in thread Thread-43:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\Package Control.py", line 4032, in run
  File ".\Package Control.py", line 3181, in install_package
  File ".\Package Control.py", line 2695, in download_url
  File ".\Package Control.py", line 1683, in download
  File ".\Package Control.py", line 1414, in check_certs
  File ".\Package Control.py", line 1451, in locate_cert
  File ".\Package Control.py", line 1478, in download_cert
NameError: global name 'domain' is not defined

ignored packages updated to: [Vintage, SublimeJava]
found 1 files for base name Default.sublime-theme
reloading /C/Users/Alvin Sim/AppData/Roaming/Sublime Text 2/Packages/User/Preferences.sublime-settings
theme loaded
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded

**Comment by enriquein** [comment]
I'll look into it. Looks like Package Manager is throwing an error. Maybe
they changed the way packages work in order to make it compatible with ST3.
I'll see what I can do.

On Friday, June 14, 2013, alvinsim wrote:

> I have the same issue but I am on Sublime version 2.0.1 build 2217 for
> windows. This is the error I see from the console:
> 
> ignored packages updated to: [Vintage, SublimeJava, JavaSetterGetter]
> found 1 files for base name Default.sublime-theme
> Exception in thread Thread-43:
> Traceback (most recent call last):
> File ".\threading.py", line 532, in __bootstrap_inner
> File ".\Package Control.py", line 4032, in run
> File ".\Package Control.py", line 3181, in install_package
> File ".\Package Control.py", line 2695, in download_url
> File ".\Package Control.py", line 1683, in download
> File ".\Package Control.py", line 1414, in check_certs
> File ".\Package Control.py", line 1451, in locate_cert
> File ".\Package Control.py", line 1478, in download_cert
> NameError: global name 'domain' is not defined
> 
> ignored packages updated to: [Vintage, SublimeJava]
> found 1 files for base name Default.sublime-theme
> reloading /C/Users/Alvin Sim/AppData/Roaming/Sublime Text
> 2/Packages/User/Preferences.sublime-settings
> theme loaded
> theme loaded
> found 1 files for base name Default.sublime-theme
> theme loaded
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/enriquein/JavaSetterGetter/issues/8#issuecomment-19463737
> .

## 

---

Enrique Ramirez Irizarry
Software Developer

**Comment by bnlucas** [comment]
It is an issue with Package Control. Possibly the packages.json file within the JavaSetterGetter repository. If you download the package and add it to the Packages directory manually, it loads just fine.

**Comment by enriquein** [comment]
Thanks for the heads up. If that's the case then it should be easy to fix.

On Friday, June 14, 2013, Nathan Lucas wrote:

> It is an issue with Package Control. Possibly the packages.json file
> within the JavaSetterGetter repository. If you download the package and add
> it to the Packages directory manually, it loads just fine.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/enriquein/JavaSetterGetter/issues/8#issuecomment-19487900
> .

## 

---

Enrique Ramirez Irizarry
Software Developer

**Comment by bnlucas** [comment]
https://github.com/enriquein/JavaSetterGetter/pull/9 Please see that, it seems to have fixed the issue.

**Comment by bnlucas** [comment]
And as for the error being raised within `Package Control.py` - `NameError: global name 'domain' is not defined` They have updated this and now references domain and timeout. [Downloader.py L98-L122](https://github.com/wbond/sublime_package_control/blob/master/package_control/downloaders/downloader.py#L98-L122) If you update Package Control, that error will go away.

**Comment by enriquein** [comment]
Seems this problem was fixed with issue #9. If not, please reopen and I'll take a stab at it.
